### ISSUE TITLE
modui-TallHealthBar is using different class colors than modui

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [gashole/modui-UnitFramesImproved#1]
UFI had the same issue at some point, but it got fixed - maybe the same fix is needed for modui-TallHealthBar?

Here's the UFI issue report: https://github.com/Ko0z/UnitFramesImproved_Vanilla/issues/4 
And this is the commits he made (i think): https://github.com/Ko0z/UnitFramesImproved_Vanilla/commit/9b421aac9d981896589575dbb9f41bd6be754711 and https://github.com/Ko0z/UnitFramesImproved_Vanilla/commit/0755832cbf59b4ecc87a0f3ba6cccc69978b34bc

**Comment by gashole** [comment]
modui-TallHealthBar uses the same [class color table](https://github.com/obble/modui/blob/master/globals/colour.lua) and statusbar texture as modui.

![http://i.imgur.com/l1kgQAJ.png](http://i.imgur.com/l1kgQAJ.png)

One of your AddOns is probably overwriting this table with new colors.

**Comment by Steffen-Hadberg-Nielsen** [comment]
Hmm... I changed a few addons to my UI yesterday and today I noticed that the colors are correct - must've been some addon overwriting like you said. Not sure which one, possibly SuperInspect or SHunterTimers.

Anyways gonna close this now 👍
