### ISSUE TITLE
Target frame doesn't show if it's a hostile (red)/neutral (yelllow) NPC target nor does it show if it's your tag or another players (gray)

### ISSUE THREAD

**Issue by Steffen-Hadberg-Nielsen** [gashole/modui-UnitFramesImproved#2]
Target frame doesn't show if it's a hostile (red)/neutral (yelllow) NPC target nor does it show if it's your tag or another players (gray)

**Comment by gashole** [comment]
Fixed by https://github.com/gashole/modui-TallHealthBar/commit/d94e888377feafbd2d836d4b49e605f6f6dcdcde
